### ISSUE TITLE
Feature Request Whitelist Implementation

### ISSUE THREAD

**Issue by StringKe** [remorses/elacca#1]
Only pages configured in the whitelist list are rendered with SSR.

```js
elacca: {
   use: ["/*"],
   skip: ["/home"]
}
```

**Comment by remorses** [comment]
is adding the “skip ssr” directive on top of the pages too much work? I want to keep this api because it’s consistent with “use client” and “use server” directives

**Comment by StringKe** [comment]
Keep the 'skip ssr' directive, I probably have over 300 pages. maybe some sort of prioritization rule could be adhered to?

directive > elacca.skip > elacca.use

**Comment by remorses** [comment]
You can use fond and replace in your editor
